### ISSUE TITLE
Variables are still in camel case.

### ISSUE THREAD

**Issue by ryan-berger** [Qwerp-Derp/beautifier#3]
It is not beautiful enough, there are capital letters in variable names

**Comment by hanyuone** [comment]
If you can figure out how to do that, sure. I'm still mainly trying to figure out a way to beautify Lisp-like languages, so I can beautify the source code for this program.

**Comment by ryan-berger** [comment]
@Qwerp-Derp I don't know clojure at all, but I could definitely write a python script if you want to port it.

**Comment by hanyuone** [comment]
@ryan-berger Porting's not that high up on the priority list, but it'd definitely be great. Thanks! (I might write a port to Dart.)

**Comment by ryan-berger** [comment]
Oh sorry, I don't mean port the whole program to python, rather just port the script that I write. I did some more research and it doesn't like there is an easy solution to this unless we used some complicated lexer to help us find variable names. I'll close this issue since it may be overkill
